apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metalb
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  project: default
  sources:
  - repoURL: 'https://metallb.github.io/metallb'
    chart: metallb
    targetRevision: 0.15.2
  - repoURL: 'https://github.com/tibo43/lima-k8s-apps.git'
    targetRevision: feat/init-project
    path: 'kubernetes/helm-tools/metalb/'
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc